name: test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-*
      - release-*
    tags:
      - v*
  # Run tests for all PRs
  pull_request:

env:
  GO_VERSION: "1.19"
  TOPAZ_CONTAINER_IMAGE: ghcr.io/aserto-dev/topaz:latest
  TOPAZ_AUTHORIZER_GRPC_PORT:  8282
  TOPAZ_AUTHORIZER_REST_PORT:  8383
  TOPAZ_DIRECTORY_GRPC_PORT:   9292
  TOPAZ_DIRECTORY_REST_PORT:   9393

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Install grpc-health-probe
        run: |
          go install github.com/grpc-ecosystem/grpc-health-probe@latest

  test:
    runs-on: ubuntu-latest
    needs:
    - pre

    services:
      topaz:
        image: ghcr.io/aserto-dev/topaz:latest
        env:
          TOPAZ_DIR: /github/workspace/_topaz
        options: >-
          run --config-file /github/workspace/_topaz/cfg/config.yaml
        ports:
          - 8282:8282
          - 8383:8383
          - 9292:9292
          - 9393:9393

    steps:
      -
        uses: actions/checkout@v3
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Install grpc-health-probe
        run: |
          go install github.com/grpc-ecosystem/grpc-health-probe@latest
      - name: Probe
        run: |
          grpc-health-probe -addr=:8484 -connect-timeout=30s -rpc-timeout=30s
      -
        name: Ping
        run: |
          curl -k 'https://localhost:8383/api/v2/info'
          curl -k 'https://localhost:8383/api/v2/policies?field_mask=id'
