name: test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-*
      - release-*
    tags:
      - v*
  # Run tests for all PRs
  pull_request:

env:
  GO_VERSION: "1.19"
  TOPAZ_CONTAINER_IMAGE: ghcr.io/aserto-dev/topaz:latest
  TOPAZ_AUTHORIZER_GRPC_PORT:  8282
  TOPAZ_AUTHORIZER_REST_PORT:  8383
  TOPAZ_DIRECTORY_GRPC_PORT:   9292
  TOPAZ_DIRECTORY_REST_PORT:   9393

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Setup caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Install grpc-health-probe
        run: |
          go install github.com/grpc-ecosystem/grpc-health-probe@latest
      -
        name: Install topaz CLI
        run: |
          go install github.com/aserto-dev/topaz/cmd/topaz@latest
      -
        name: Topaz Install
        run: |
          topaz install
      -
        name: Topaz Configure
        run: |
          topaz configure --policy-name=test --resource=ghcr.io/aserto-policies/policy-template:latest
      -
        name: Topaz Start
        run: |
          topaz start --container-name="topaz" --container-version="latest" --hostname=localhost
      -
        name: Dump directory
        run: |
          find ~/.config/topaz -type f
      -
        name: Topaz Health Check
        run: |
          grpc-health-probe -addr=localhost:8484 -connect-timeout=120s -rpc-timeout=120s
      -
        name: Dump directory
        run: |
          find ~/.config/topaz -type f
      -
        name: Ping
        run: |
          curl -k 'https://localhost:8383/api/v2/info'
          curl -k 'https://localhost:8383/api/v2/policies?field_mask=id'
      -
        name: Topaz Load Manifest
        run: |
          topaz load ./model/manifest.yaml --insecure --no-check
      -
        name: Topaz Load Data
        run: |
          topaz import --directory=./data --insecure --no-check
      -
        name: Topaz Exec Test
        run: |
          topaz test exec ./test/assertions.json --insecure --no-check
