name: test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
      - dev-*
      - release-*
    tags:
      - v*
  # Run tests for all PRs
  pull_request:

env:
  GO_VERSION: "1.19"
  CONTAINER_NAME: topaz
  CONTAINER_VERSION: latest
  POLICY_NAME: roblox
  POLICY_IMAGE: ghcr.io/aserto-proj/roblox:latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        name: Install grpc-health-probe
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      -
        name: Install topaz CLI
        run: |
          go install github.com/aserto-dev/topaz/cmd/topaz@latest
      -
        name: Topaz Install
        run: |
          topaz install
      -
        name: Topaz Configure
        run: |
          topaz configure --policy-name=${{ env.POLICY_NAME }} --resource=${{env.POLICY_IMAGE}}
      -
        name: Topaz Start
        run: |
          topaz start --container-name=${{ env.CONTAINER_NAME }} --container-version=${{ env.CONTAINER_VERSION }} --hostname=localhost
      -
        name: Topaz Health Check
        run: |
          grpc-health-probe -addr=localhost:8484 -connect-timeout=120s -rpc-timeout=120s
      -
        name: Dump directory
        run: |
          find ~/.config/topaz -type f
          find . -type f
      -
        name: Ping
        run: |
          curl -k 'https://localhost:8383/api/v2/info'
          curl -k 'https://localhost:8383/api/v2/policies?field_mask=id'
      -
        name: Topaz Load Manifest
        run: |
          topaz load ./model/manifest.yaml --insecure --no-check
      -
        name: Topaz Load Data
        run: |
          topaz import --directory=./data --insecure --no-check
      -
        name: Topaz Exec Test (directory)
        run: |
          topaz test exec ./test/assertions.json --insecure --no-check
      -
        name: Topaz Exec Test (authorizer)
        run: |
          topaz test exec ./test/decisions.json --insecure --no-check
